[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/liveness/*"
  to = "http://173.249.19.250:8000/liveness/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
